(ns utils-test
  (:require [config :refer [CONSTANTS]]
            [utils :refer :all]
            [test-setup :refer :all]
            [clojure.test :refer :all]
            [babashka.fs :as fs]))

(use-fixtures :once load-test-paths load-rdfs-parsed load-model-records)

(deftest count-dict-test
  (is (= (count-dict {:a [1 2] :b [4 5 6]}) {:a 2 :b 3})))

(deftest select-key->vec-test
  (is (= (select-key->vec {:a 1 :b "2"} :b) [:b "2"])))

(deftest get-parent-components-test
  (testing "Using 2 arguments on a generic path"
    (let [a-path (fs/path "a_root" "first_folder" "second_folder" "file.txt")
          parent-comp (get-parent-components "a_root" a-path)
          expected-comp ["first_folder" "second_folder"]]
      (is (= (map str parent-comp) expected-comp))))
  (testing "Using only 1 argument (default COLLECTION-ROOT)"
    (let [parent-comp (get-parent-components @(:an-rdf rdf-paths))
          expected-parent-comp ["10.5281" "zenodo.6334881" "6346477"]]
      (is (= (map str parent-comp) expected-parent-comp)))))

(deftest new-root-path-test
  (let [a-path (fs/path "a_root" "first_folder" "second_folder" "file.txt")
        expect (fs/path "a_new_root" "first_folder" "second_folder")]
    (is (= (str expect) (str (new-root-path "a_root" "a_new_root" a-path))))))

(deftest before-str-content-test
  (is (= (before-str-content "first line \n## second line" "##") ["first line \n" " second line"]))
  (is (= (before-str-content "first line \n## second line" "## second line") ["first line \n"]))
  (let [s1 "Branch with all the test summaries generated by the CI.\r\n"
        s3 "other things..."
        content (str s1 (:summa-readme-header CONSTANTS) s3)]
    (is (= (before-str-content content (:summa-readme-header CONSTANTS)) [s1 s3]))
    (is (= (before-str-content "abc" (:summa-readme-header CONSTANTS)) ["abc"]))))

(deftest original-file-content-test
  (let [temp-file "temp.txt"]
    (is (= (original-file-content "no.txt" "##") ""))
    (spit temp-file (str "Branch with all the test summaries generated by the CI." \newline))
    (is (= (original-file-content temp-file "##") (slurp temp-file)))
    (fs/delete-if-exists temp-file)))
