name: clj CI - test BioImage.IO resources with DeepImageJ

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab (github website)
  workflow_dispatch:
    inputs:
      pending_matrix:
        description: 'json encoded gh matrix of pending validations for new or updated resources (default: test on all resources)'
        required: true
        #default: '''{"include": [{"resource_id": "**", "version_id": "**"}]}'''
        default: '''{"include": [{"resource_id": "10.5281/zenodo.7261974","version_id": "7261975"},
        {"resource_id": "deepimagej","version_id": "DeepSTORMZeroCostDL4Mic/latest"},
        {"resource_id": "10.5281/zenodo.6334881","version_id": "6346477"}]}'''
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my-ci-job:
    runs-on: windows-latest # HAS TO BE ON WINDOWS SINCE DIJ3.03 HAS WEIRD LINUX HEADLESS BUG

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Check out another repository
      - uses: actions/checkout@v3
        with:
          repository: bioimage-io/collection-bioimage-io
          ref: gh-pages
          path: bioimageio-gh-pages
      - uses: actions/checkout@v3
        with:
          repository: ivan-ea/numpy-tiff-deepimagej
          ref: master
          path: numpy-tiff-deepimagej

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world! ${{ inputs.pending_matrix }}

      - name: setup babashka
        uses: turtlequeue/setup-babashka@v1.5.0
        with:
          babashka-version: 1.1.173

      - name: Setup fiji & deepimagej
        working-directory: ./java_CI_scripts 
        run: |
          bb "(require '[reproduce.setup-fiji :as r]) (r/setup-fiji-&-deepimagej3)"

      - name: run initial stage
        working-directory: ./java_CI_scripts
        run: |
          bb --version
          bb -m core.main -s ${{ inputs.pending_matrix }} download
          ls -R -l ../models          

      - name: run reproduce pipeline
        working-directory: ./java_CI_scripts
        run: |
          bb --version
          bb -m core.main reproduce

      - name: upload the test summaries
        uses: actions/upload-artifact@v3
        with:
          name: test-summaries
          path: ./test_summaries/
          retention-days: 1

  deploy:
    needs: my-ci-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: test-summaries
        path: ./test_summaries/

    - name: exploratory commands
      run: |
        chmod +x ./bash_scripts/explore_commands.sh
        bash ./bash_scripts/explore_commands.sh

    - name: Deploy test summaries to gh-pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        clean: false
        branch: gh-pages
        folder: ./test_summaries
      
